version: "3"
services:
  hub: 
    image: selenium/hub:4.19.1
    #ports:
    #- 4444:4444
    # - 4442:4442  //These are only for communication between containers
    # - 4443:4443  // so they do not need to be exposed
  chrome:
    image: selenium/node-chrome:4.19.1
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 1
    env_file: .env
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
  firefox:
    image: selenium/node-firefox:4.19.1
    shm_size: '2g'
    depends_on:
    - hub
    deploy:
      replicas: 1
    env_file: .env


    
